# java异常处理
## 异常的结构

![img](https://pic1.zhimg.com/v2-3733e690763f0fe1f7614ed658b7b2d8_b.png)

#### 异常分类  
异常对象都是派生于Throwable类的一个实例，并可以自行创建异常类。  
#### Error
Error类层描述运行时系统的内部错误和资源耗尽，**应用层不应该throw这种类型的对象**   。通常为虚拟机异常如 StackOverflowError
#### Exception
- RuntimeException

  **程序员的问题的问题**，错误的类型访问，数组访问越界，访问空指针等

- 其他IO之类的

### 受检异常和非受检异常

* 受检异常会在编译时被检测。如果一个方法中的代码会抛出受检异常，则该方法必须包含异常处理，即 try-catch 代码块，或是用 throws 关键字声明该方法可能会抛出该受检异常，否则编译无法通过。

* 非受检异常为不会在编译时被检测。 Java 中 Error 和 RuntimeException 类的子类属于非受检异常，除此之外继承自 Exception 的类型为受检异常

Error类或RuntimeException类的所有异常成为`unchecked异常`，其他为`checked异常`  
抛出异常例如：
> public FileInput(String name) throws FileNotFoundException{}

表示构造器将根据给定的String参数产生一个FIleInputStream对象，但也可能抛出一个FileNotFoundException异常，如果发生错误将不会初始化一个FIS对象而是一个FNFE对象。如果抛出了异常对象，运行时会开始搜索异常处理器，以便知道如何处理异常对象  
一下4种情况应抛出异常：
- 调用一个已检查异常的方法
- 程序运行过程中发现错误，并且利用`throw语句`抛出一个已检查异常
- 程序出现错误，例如越界
- Java虚拟机和运行时库出现内部错误

前两种一定要抛出异常或捕获处理，不然线程结束  
应声明checked异常，不应声明从Runtime Exception继承的unchecked异常
#### 如何抛出异常
利用throw语句
>if(!a)
    throw new EOFExcpetion();
可以增加描述异常语句
    throw new EOFExcpetion("this is a Exception")

#### 创建异常
创建一个派生于Exception或其子类的类  

``` java
class FileFormatException extends IOException{
  public FileFormatException(){}
  public FileFormatException(String gripe){
    super(gripe);
  }
}
```
#### 捕获异常
如果异常不捕获，那么程序就会终止，并且在控制台打印出异常信息，包括异常的累哦行以及堆栈的内容
```
    try{
      code
      morecode
    }catch(ExceptionType e){
      handler for this type
    }catch(ExceptionType e){
      handler for this type
      e.getMessage();//得到详细错误信息
      e.getClass();//得到异常对象的实际类型
    }finally{
      do things
    }

```
catch也可以抛出异常，例如记录或封装：  
``` java
catch(SQLExceptioin e){
  Throwable se=new ServletException("database error")
  logger.log(level,message,e);
  se.initCause(e);
  throw se;
}
```
catch到异常后如果继续throw则执行finally里的代码不执行后的代码  
try到异常缺没catch到则执行finally不执行后面的代码，其他情况顺序执行直到throw  
可以使用finally来close资源，语句可简化为：
```java
try(Resource res = bala,...){
  work with res
}//相当于finally{res.close(),...}

```

#### 分析堆栈跟踪元素  
stack trace 是一个`方法调用过程`的列表，包含了程序执行过程中方法调用的位置，当java程序终止而没有捕获异常的话，就会打印出列表。  
也可以直接打印出堆栈跟踪信息如：
```java
public static int f(int n){
        System.out.println("f"+n);
        Throwable t=new Throwable();
        StackTraceElement[] frames=t.getStackTrace();
        for(StackTraceElement frame:frames){
            System.out.println(frame);
        }
        if(n==1)return 1;
        return f(n-1)*n;
    }
    public static void main(String[] args) {
        f(3);
    }
结果如下：
f3
com.exception.TryToStack.f(TryToStack.java:10)
com.exception.TryToStack.main(TryToStack.java:20)
f2
com.exception.TryToStack.f(TryToStack.java:10)
com.exception.TryToStack.f(TryToStack.java:16)
com.exception.TryToStack.main(TryToStack.java:20)
f1
com.exception.TryToStack.f(TryToStack.java:10)
com.exception.TryToStack.f(TryToStack.java:16)
com.exception.TryToStack.f(TryToStack.java:16)
com.exception.TryToStack.main(TryToStack.java:20)
```
#### 断言
一共两种形式：  
- assert expression;
- assert expression:表达式;  //可以在堆栈打印出表达式转化的消息字符串  

在运行时在VM options加入-ea参数，即可调用断言  
关闭时自动跳过断言代码块  

### 日志  
可以调用getLogger创建或检索记录器：
```java
private static final Logger myLogger=new Logger.getLogger("com.company.mylog")
```
日志记录器也有层次结构并且父子间可共享某些属性如：设置权限  
- SEVER
- WARNING
- INFO
- CONFIG
- FINE
- FINER
- FINEST

默认情况记录前三等级，可通过`logger.setLevel(LEVEL.FINE)`设置，参数还可以有`LEVEL.ALL or LEVEL.OFF`  
可调用的方法 待补充

## 功利部分

- **Error 和 Exception 区别是什么？**
  Error 类型的错误通常为虚拟机相关错误，如系统崩溃，内存不足，堆栈溢出等，编译器不会对这类错误进行检测，JAVA 应用程序也不应对这类错误进行捕获，一旦这类错误发生，通常应用程序会被终止，仅靠应用程序本身无法恢复；

  Exception 类的错误是可以在应用程序中进行捕获并处理的，通常遇到这种错误，应对其进行处理，使应用程序可以继续正常运行。

- **运行时异常和一般异常区别是什么？**
  编译器不会对运行时异常进行检测，没有 try-catch，方法签名中也没有 throws 关键字声明，编译依然可以通过。如果出现了 RuntimeException, 那一定是程序员的错误。

  一般异常如果没有 try-catch，且方法签名中也没有用 throws 关键字声明可能抛出的异常，则编译无法通过。这类异常通常为应用环境中的错误，即外部错误，非应用程序本身错误，如文件找不到等。

- **NoClassDefFoundError 和 ClassNotFoundException 区别是什么？**
  NoClassDefFoundError 是一个 Error 类型的异常，是由 JVM 引起的，不应该尝试捕获这个异常。引起该异常的原因是 JVM 或 ClassLoader 尝试加载某类时在内存中找不到该类的定义，该动作发生在运行期间，即编译时该类存在，但是在运行时却找不到了，可能是变异后被删除了等原因导致；

  ClassNotFoundException 是一个受查异常，需要显式地使用 try-catch 对其进行捕获和处理，或在方法签名中用 throws 关键字进行声明。当使用 Class.forName, ClassLoader.loadClass 或 ClassLoader.findSystemClass 动态加载类到内存的时候，通过传入的类路径参数没有找到该类，就会抛出该异常；另一种抛出该异常的可能原因是某个类已经由一个类加载器加载至内存中，另一个加载器又尝试去加载它。

- **JVM 是如何处理异常的？**
  在一个方法中如果发生异常，这个方法会创建一个一场对象，并转交给 JVM，该异常对象包含异常名称，异常描述以及异常发生时应用程序的状态。创建异常对象并转交给 JVM 的过程称为抛出异常。可能有一系列的方法调用，最终才进入抛出异常的方法，这一系列方法调用的有序列表叫做调用栈。
  JVM 会顺着调用栈去查找看是否有可以处理异常的代码，如果有，则调用异常处理代码。当 JVM 发现可以处理异常的代码时，会把发生的异常传递给它。如果 JVM 没有找到可以处理该异常的代码块，​​​​JVM 就会将该异常转交给默认的异常处理器（默认处理器为 JVM 的一部分），默认异常处理器打印出异常信息并终止应用程序。

- **throw 和 throws 的区别是什么？**
  throw 关键字用来抛出方法或代码块中的异常，受查异常和非受查异常都可以被抛出。
  throws 关键字用在方法签名处，用来标识该方法可能抛出的异常列表。一个方法用 throws 标识了可能抛出的异常列表，调用该方法的方法中必须包含可处理异常的代码，否则也要在方法签名中用 throws 关键字声明相应的异常。​​

- **常见的 RuntimeException 有哪些？**

1. ClassCastException(类转换异常)
2. IndexOutOfBoundsException(数组越界)
3. NullPointerException(空指针)
4. ArrayStoreException(数据存储异常，操作数组时类型不一致)
5. 还有IO操作的BufferOverflowException异常

